const registerAuthRoutes = require('./v1/auth');
const registerTaskRoutes = require('./v1/tasks');
const registerCategoryRoutes = require('./v1/categories');
const registerTopicRoutes = require('./v1/topics');
const registerDifficultyRoutes = require('./v1/difficulties');
const registerDifficultyLevelRoutes = require('./v1/difficultyLevels');
const registerQuestionStyleRoutes = require('./v1/questionStyles');
const registerQuestionCountRoutes = require('./v1/questionCounts');
const registerTestAttemptRoutes = require('./v1/testAttempts');
const registerAiCurationRoutes = require('./v1/aiCuration');
const registerUserRoutes = require('./v1/users');
const registerExamHierarchyRoutes = require('./v1/examHierarchy');
const registerExamRoutes = require('./v1/exam');
const registerQuestionBankRoutes = require('./v1/questionBank');
const registerPaperBlueprintRoutes = require('./v1/paperBlueprints');
const registerAiGenerationJobRoutes = require('./v1/aiGenerationJobs');
const registerSystemRoutes = require('./v1/system');
const registerMotivationalQuoteRoutes = require('./v1/motivationalQuote');
const registerAdminMotivationalQuoteRoutes = require('./v1/admin/motivationalQuotes');
const registerAdminSarkariJobUpdateRoutes = require('./v1/admin/sarkariJobUpdates');
const registerSarkariJobUpdateRoutes = require('./v1/sarkariJobUpdates');
const registerAnalyticsRoutes = require('./v1/analytics');
const registerEngagementAnalyticsRoutes = require('./v1/engagementAnalytics');
const registerSubscriptionPlanRoutes = require('./v1/subscriptionPlans');
const registerUserSubscriptionRoutes = require('./v1/userSubscriptions');
const registerPaytmRoutes = require('./v1/paytm');
const registerReferralRoutes = require('./v1/referrals');
const registerAdminReferralRoutes = require('./v1/admin/referrals');

module.exports = (app) => {
  registerAuthRoutes(app);
  registerUserRoutes(app);
  registerTaskRoutes(app);
  registerCategoryRoutes(app);
  registerTopicRoutes(app);
  registerDifficultyRoutes(app);
  registerDifficultyLevelRoutes(app);
  registerQuestionStyleRoutes(app);
  registerQuestionCountRoutes(app);
  registerExamHierarchyRoutes(app);
  registerExamRoutes(app);
  registerPaperBlueprintRoutes(app);
  registerAiGenerationJobRoutes(app);
  registerSystemRoutes(app);
  registerAnalyticsRoutes(app);
  registerEngagementAnalyticsRoutes(app);
  registerQuestionBankRoutes(app);
  registerTestAttemptRoutes(app);
  registerAiCurationRoutes(app);
  registerMotivationalQuoteRoutes(app);
  registerAdminMotivationalQuoteRoutes(app);
  registerAdminSarkariJobUpdateRoutes(app);
  registerSarkariJobUpdateRoutes(app);
  registerSubscriptionPlanRoutes(app);
  registerUserSubscriptionRoutes(app);
  registerPaytmRoutes(app);
  registerReferralRoutes(app);
  registerAdminReferralRoutes(app);
};
