const registerAuthRoutes = require('./v1/auth');
const registerTaskRoutes = require('./v1/tasks');
const registerCategoryRoutes = require('./v1/categories');
const registerTopicRoutes = require('./v1/topics');
const registerDifficultyRoutes = require('./v1/difficulties');
const registerDifficultyLevelRoutes = require('./v1/difficultyLevels');
const registerQuestionStyleRoutes = require('./v1/questionStyles');
const registerQuestionCountRoutes = require('./v1/questionCounts');
const registerTestAttemptRoutes = require('./v1/testAttempts');
const registerAiCurationRoutes = require('./v1/aiCuration');
const registerUserRoutes = require('./v1/users');
const registerExamHierarchyRoutes = require('./v1/examHierarchy');
const registerQuestionBankRoutes = require('./v1/questionBank');
const registerPaperBlueprintRoutes = require('./v1/paperBlueprints');
const registerAiGenerationJobRoutes = require('./v1/aiGenerationJobs');
const registerSystemRoutes = require('./v1/system');

module.exports = (app) => {
  registerAuthRoutes(app);
  registerUserRoutes(app);
  registerTaskRoutes(app);
  registerCategoryRoutes(app);
  registerTopicRoutes(app);
  registerDifficultyRoutes(app);
  registerDifficultyLevelRoutes(app);
  registerQuestionStyleRoutes(app);
  registerQuestionCountRoutes(app);
  registerExamHierarchyRoutes(app);
  registerPaperBlueprintRoutes(app);
  registerAiGenerationJobRoutes(app);
  registerSystemRoutes(app);
  registerQuestionBankRoutes(app);
  registerTestAttemptRoutes(app);
  registerAiCurationRoutes(app);
};
